//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoProway
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assistido
    {
        public int IdAssistido { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public Nullable<int> FilmeId { get; set; }
        public Nullable<int> SerieId { get; set; }
        public Nullable<System.DateTime> Em { get; set; }
    
        public virtual Filme Filme { get; set; }
        public virtual Serie Serie { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
