//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoProway
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BancoEntities : DbContext
    {
        public BancoEntities()
            : base("name=BancoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assistido> Assistido { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Episodio> Episodio { get; set; }
        public virtual DbSet<Filme> Filme { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<Serie> Serie { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Temporada> Temporada { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
