//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoProway
{
    using System;
    using System.Collections.Generic;
    
    public partial class Episodio
    {
        public int IdEpisodio { get; set; }
        public Nullable<int> TemporadaId { get; set; }
        public Nullable<int> Sequencial { get; set; }
        public string Nome { get; set; }
        public string Sinopse { get; set; }
    
        public virtual Temporada Temporada { get; set; }
    }
}
