//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoProway
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Filme()
        {
            this.Assistido = new HashSet<Assistido>();
        }
    
        public int IdFilme { get; set; }
        public Nullable<int> CategoriaId { get; set; }
        public string Nome { get; set; }
        public Nullable<int> Ano { get; set; }
        public string Sinopse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assistido> Assistido { get; set; }
        public virtual Categoria Categoria { get; set; }
    }
}
